name: 'Sync Issue Label to Project Field Action'
description: 'Finds all values for the specified fields, then set's the field value on every item that has a matching label' 
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: green
inputs:
  owner-name:
    description: 'The owning organization/user for the project'
    type: string
    required: true
  project-id:
    description: 'The id of the project'
    type: number
    required: true
  field-name:
    description: 'The field to reference for the project'
    type: string
    required: true
  label-overrides:
    description: 'If multiple labels map to a single field value, include the mapping here'
    type: string
    required: false
  
  